name: Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn build
      - name: Lint
        run: yarn lint
